### ISSUE TITLE
CAESAR downloads

### ISSUE THREAD

**Issue by YeeZ93** [DavidBoja/pose-independent-anthropometry#1]
Thanks so much for the inspiring work!

Could you please provide a link by which people are able to download the CAESAR dataset?

Thanks in advance!

**Comment by DavidBoja** [comment]
Thank you!
Unfortunately, the CAESAR dataset is commercial and you can buy it [here](https://www.bodysizeshape.com/page-1855750).

**Comment by YeeZ93** [comment]
> Thank you! Unfortunately, the CAESAR dataset is commercial and you can buy it [here](https://www.bodysizeshape.com/page-1855750).

Oh, well noted ,thx!
